name: Flujo de trabajo para la app TestDevopsMusicApp

on:
  push:
    branches:
      - master

jobs:
  build-backend:
    runs-on: windows-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2
      with:
        path: TestDevopsMusicApp

    - name: Instalar Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Instalar dependencias
      run: cd ${{ github.workspace }} backend && npm install

    - name: Construir Docker
      run: |
        docker build -t img-backend:${{ github.sha }} -f backend/Dockerfile ${{ github.workspace }}/backend
        docker push img-backend:${{ github.sha }}

  build-frontend:
    runs-on: windows-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2
      with:
        path: TestDevopsMusicApp

    - name: Instalar Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Instalar dependencias
      run: cd ${{ github.workspace }} && npm install

    - name: Ejecutar pruebas con Cypress
      run: cd ${{ github.workspace }} && npx cypress run

    - name: Construir Docker
      run: |
        docker build -t img-frontend:${{ github.sha }} -f frontend/Dockerfile ${{ github.workspace }}/frontend
        docker push img-frontend:${{ github.sha }}